###############################################################################
#
#    Service Config section
#
###############################################################################
server:
  port: 4000,4001
  mode: debug  # debug;release
  gorm:
    LogMode: false # db log
  view:
    limit: 10 
  passphrase: "tDydrX7ia8Zx6Vwr"  # rand
  key: "VeZ16GuXyKaYhKbA"  # api key rand        

###############################################################################
#
#    MariaDb Config section
#
###############################################################################

database:
  dialect: mysql
  database: coupon
  # database: bookmarker
  user: root
  password: yiyun88
  # 要支持emoji的话，填 utf8mb4
  charset: utf8mb4
  # 数据库ip 
  host: 127.0.0.1
  # 数据库端口
  port: 3306
  # 空闲时最大的连接数
  maxIdleConns: 20
  # 最大的连接数
  maxOpenConns: 20

###############################################################################
#
#    JWT Config section
#
###############################################################################

jwt:
  signing_key: "MLex9TWrEMxv7ytu"
  expire: 60
  realm: "coupon io"
